echo "this is my first jenkins demo project"
echo "naresh is a devops engineer"
echo "this system host name is : `hostname`"
echo "jenkins workspace dir is `pwd`"
echo "hai"
ech0 "iam a devops engineer"
echo "hi how are you"
